import createClient from "openapi-fetch";
import type {paths} from "./schema"; // generated by openapi-typescript

const prepareHeaders = () => {
    const apikey = import.meta.env.VITE_API_KEY
    if (!apikey) return undefined

    return {
        'api-key': apikey
    }
}

export const client = createClient<paths>({
    baseUrl: "https://musicfun.it-incubator.app/api/1.0/",
    headers: prepareHeaders()
})
