import createClient, {type Middleware} from "openapi-fetch";
import type {paths} from "./schema"; // generated by openapi-typescript

// mutex
let refreshPromise: Promise<void> | null = null

function makeRefreshToken() {
    if (!refreshPromise) {
        refreshPromise = (async (): Promise<void> => {
            const refreshToken = localStorage.getItem('musicfun-refresh-token')
            if (!refreshToken) throw new Error("No refresh token")



        })()

        refreshPromise.finally(() => {
            refreshPromise = null
        })
    }
}

const prepareHeaders = () => {
    const apikey = import.meta.env.VITE_API_KEY
    if (!apikey) return undefined

    return {
        'api-key': apikey
    }
}

const authMiddleware: Middleware = {
    onRequest({ request }) {
        // set "foo" header
        const accessToken = localStorage.getItem('musicfun-access-token')
        if (accessToken) {
            request.headers.set("Authorization", "Bearer " + accessToken)
        }
        return request;
    },
    onResponse({ response }) {
        if (!response.ok) {
            throw new Error(`${response.url}: ${response.status} ${response.statusText}`)
        }
    }
}

export const client = createClient<paths>({
    baseUrl: "https://musicfun.it-incubator.app/api/1.0/",
    headers: prepareHeaders()
})

client.use(authMiddleware)
